### ISSUE TITLE
ImportError: cannot import name 'FakeRepo'

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#136]
When trying to run pkgcheck on martin.g.o, I get:

```
$ pkgcheck scan -r gentoo
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 48, in _GET_VALS
    result = getattr(_defaults, attr)
AttributeError: 'object' object has no attribute 'KEYWORDS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/__init__.py", line 31, in run
    tool = Tool(script.argparser)
  File "/usr/lib64/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/pkgcheck.py", line 33, in <module>
    from .. import base, feeds, const, reporters
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 56, in <module>
    'KEYWORDS', partial(_find_obj_classes, 'checks', base.Result)))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 50, in _GET_VALS
    result = func()
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 39, in _find_obj_classes
    for name, cls in inspect.getmembers(m):
  File "/usr/lib64/python3.6/inspect.py", line 320, in getmembers
    if isclass(object):
  File "/usr/lib64/python3.6/inspect.py", line 79, in isclass
    return isinstance(object, type)
  File "/usr/lib64/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/checks/acct.py", line 8, in <module>
    from .. import base, sources
  File "/usr/lib64/python3.6/site-packages/pkgcheck/sources.py", line 6, in <module>
    from . import addons, base
  File "/usr/lib64/python3.6/site-packages/pkgcheck/addons.py", line 19, in <module>
    from pkgcore.test.misc import FakeRepo
ImportError: cannot import name 'FakeRepo'
```

Might be because it's using rsync checkout.

**Comment by radhermit** [comment]
Give me the output from ``qlist pkgcheck | grep const`` or similar on the machine. It shouldn't even be hitting that codepath if it's installed properly.

**Comment by mgorny** [comment]
```
$ qlist pkgcheck | grep cons
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/_const.cpython-36.opt-2.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/const.cpython-36.opt-2.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/const.cpython-36.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/_const.cpython-36.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/const.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/_const.py
/usr/lib64/python3.6/site-packages/pkgcheck/const.py

**Comment by mgorny** [comment]
And before you ask, I've tried rebuilding all three packages already.

```
dev-python/snakeoil-0.8.1::gentoo was built with the following:
USE="-test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"


sys-apps/pkgcore-0.10.1::gentoo was built with the following:
USE="-doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"


dev-util/pkgcheck-0.6.2::gentoo was built with the following:
USE="-doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"
```

**Comment by radhermit** [comment]
What's the output from: ``python -c 'from pkgcheck import _const as const; print("\n".join(x for x, y in const.KEYWORDS))'`` ?

**Comment by radhermit** [comment]
Also, I probably see the problem, the generated _const module isn't getting byte-compiled with optimizations and you're running some level of -O on the machine so it isn't getting used.

**Comment by radhermit** [comment]
Or rather, it's lacking the opt-1 level.

**Comment by radhermit** [comment]
See if 0.6.3 works for you now.

**Comment by mgorny** [comment]
Fails the same.

```
=================================================================
                        Package Settings
=================================================================

dev-python/snakeoil-0.8.2::gentoo was built with the following:
USE="-test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"


sys-apps/pkgcore-0.10.2::gentoo was built with the following:
USE="-doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"


dev-util/pkgcheck-0.6.3::gentoo was built with the following:
USE="-doc -test" ABI_X86="(64)" PYTHON_TARGETS="python3_6 -python3_7"


$ qlist pkgcheck | grep const
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/_const.cpython-36.opt-2.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/const.cpython-36.opt-2.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/_const.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/const.cpython-36.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/_const.cpython-36.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/__pycache__/const.cpython-36.opt-1.pyc
/usr/lib64/python3.6/site-packages/pkgcheck/_const.py
/usr/lib64/python3.6/site-packages/pkgcheck/const.py

$ pkgcheck
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 49, in _GET_VALS
    result = getattr(_defaults, attr)
AttributeError: 'object' object has no attribute 'KEYWORDS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/__init__.py", line 31, in run
    tool = Tool(script.argparser)
  File "/usr/lib64/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/pkgcheck.py", line 28, in <module>
    from .. import base, const, reporters
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 57, in <module>
    'KEYWORDS', partial(_find_obj_classes, 'checks', base.Result)))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 51, in _GET_VALS
    result = func()
  File "/usr/lib64/python3.6/site-packages/pkgcheck/const.py", line 40, in _find_obj_classes
    for _name, cls in inspect.getmembers(m):
  File "/usr/lib64/python3.6/inspect.py", line 320, in getmembers
    if isclass(object):
  File "/usr/lib64/python3.6/inspect.py", line 79, in isclass
    return isinstance(object, type)
  File "/usr/lib64/python3.6/importlib/util.py", line 233, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/checks/acct.py", line 10, in <module>
    from .. import base, sources
  File "/usr/lib64/python3.6/site-packages/pkgcheck/sources.py", line 7, in <module>
    from . import addons, base
  File "/usr/lib64/python3.6/site-packages/pkgcheck/addons.py", line 18, in <module>
    from pkgcore.test.misc import FakeRepo
ImportError: cannot import name 'FakeRepo'
```

Interesting thing is, there's no lxml on this system somehow. Maybe that's the culprit.

**Comment by mgorny** [comment]
Indeed, installing lxml fixes it. Now to figure out why the damn thing gets removed…

**Comment by radhermit** [comment]
I could conditionally disable lazy imports for the namespace walking part of that code so it would output that actual underlying lxml import error for the next person who runs into this.

**Comment by mgorny** [comment]
Well, yes, it would be nice to see the correct error message ;-).
