### ISSUE TITLE
AttributeError: module 'email.parser' has no attribute 'Parser'

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#153]
```
$ pkgcheck scan --net --git-disable $(git diff origin --name-only $(<profiles/categories) | cut -d/ -f1-2 | sort -u)
dev-python/pyalsa
  DeprecatedEAPI: version 1.0.29: uses deprecated EAPI 5
ERROR concurrent.futures: exception calling callback for <Future at 0x7f72ee031390 state=finished raised AttributeError>
ERROR concurrent.futures: Traceback (most recent call last):
ERROR concurrent.futures:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
ERROR concurrent.futures:     callback(self)
ERROR concurrent.futures:   File "/usr/lib/python3.7/site-packages/pkgcheck/checks/network.py", line 147, in _done
ERROR concurrent.futures:     result = future.result()
ERROR concurrent.futures:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
ERROR concurrent.futures:     return self.__get_result()
ERROR concurrent.futures:   File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
ERROR concurrent.futures:     raise self._exception
ERROR concurrent.futures:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
ERROR concurrent.futures:     result = self.fn(*self.args, **self.kwargs)
ERROR concurrent.futures:   File "/usr/lib/python3.7/site-packages/pkgcheck/checks/network.py", line 121, in _url_to_result
ERROR concurrent.futures:     response = self.url_opener.open(url, timeout=self.timeout)
ERROR concurrent.futures:   File "/usr/lib/python3.7/urllib/request.py", line 525, in open
ERROR concurrent.futures:     response = self._open(req, data)
ERROR concurrent.futures:   File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
ERROR concurrent.futures:     '_open', req)
ERROR concurrent.futures:   File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
ERROR concurrent.futures:     result = func(*args)
ERROR concurrent.futures:   File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
ERROR concurrent.futures:     context=self._context, check_hostname=self._check_hostname)
ERROR concurrent.futures:   File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
ERROR concurrent.futures:     r = h.getresponse()
ERROR concurrent.futures:   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
ERROR concurrent.futures:     response.begin()
ERROR concurrent.futures:   File "/usr/lib/python3.7/http/client.py", line 330, in begin
ERROR concurrent.futures:     self.headers = self.msg = parse_headers(self.fp)
ERROR concurrent.futures:   RedundantVersion: version 1.0.29: slot(0) keywords are overshadowed by version: 1.1.6
  File "/usr/lib/python3.7/http/client.py", line 224, in parse_headers
ERROR concurrent.futures:     return email.parser.Parser(_class=_class).parsestr(hstring)
ERROR concurrent.futures: AttributeError: module 'email.parser' has no attribute 'Parser'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.7/site-packages/pkgcheck/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 182, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 167, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.7/site-packages/pkgcheck/scripts/pkgcheck.py", line 523, in _scan
    for result in base.Pipeline(pipes, filterer).run():
  File "/usr/lib/python3.7/site-packages/pkgcheck/base.py", line 739, in run
    yield from self.pipes[i].feed(item)
  File "/usr/lib/python3.7/site-packages/pkgcheck/base.py", line 769, in feed
    yield from reports
  File "/usr/lib/python3.7/site-packages/pkgcheck/checks/network.py", line 171, in feed
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.7/site-packages/pkgcheck/checks/network.py", line 147, in _done
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/pkgcheck/checks/network.py", line 121, in _url_to_result
    response = self.url_opener.open(url, timeout=self.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 330, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/lib/python3.7/http/client.py", line 224, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
AttributeError: module 'email.parser' has no attribute 'Parser'

**Comment by mgorny** [comment]
Hmm, now that I look at it, it seems like a bug in Python3.7. Sorry.

**Comment by mgorny** [comment]
That said, if you could try to reproduce and/or prepare minimal reproducer for me and/or take it upstream, that'd be much appreciated.

**Comment by radhermit** [comment]
I switched to using requests for everything except ftp:// URLs in git so this isn't relevant to pkgcheck anymore, i.e. I don't think I'll be able to reproduce it now.

**Comment by mgorny** [comment]
Happens with requests as well.

**Comment by radhermit** [comment]
Similar backtrace?

**Comment by mgorny** [comment]
Yes, just `requests` appears in the middle ;-). Can't you reproduce with py3.7? Maybe my install is broken somehow. I'll rebuild it shortly.

**Comment by mgorny** [comment]
This is really weird. The code in CPython looks fine, and it hasn't been touched since 2009. I suspect pkgcore is doing something hacky that breaks it.
