### ISSUE TITLE
`ValueError: write to closed file` when combining `--net` with piped output

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#156]
```
$ pkgcheck scan --net */hsa-ext-rocr | cat
dev-libs/hsa-ext-rocr
  UnstableOnly: for arch: [ amd64 ], all versions are unstable: [ 1.1.9.99 ]
ERROR concurrent.futures: exception calling callback for <Future at
                        : 0x7f7022738850 state=finished returned partial>
ERROR concurrent.futures: Traceback (most recent call last):
ERROR concurrent.futures:   File
                        : "/usr/lib/python3.7/concurrent/futures/_base.py",
                        : line 324, in _invoke_callbacks
ERROR concurrent.futures:     callback(self)
ERROR concurrent.futures:   File
                        : "/usr/lib/python3.7/site-packages/pkgcheck/checks/net
                        : work.py", line 150, in _done
ERROR concurrent.futures:     self.options.reporter.report(result(pkg=pkg))
ERROR concurrent.futures:   File
                        : "/usr/lib/python3.7/site-packages/pkgcheck/base.py",
                        : line 444, in _add_report
ERROR concurrent.futures:     self.process(result)
ERROR concurrent.futures:   File
                        : "/usr/lib/python3.7/site-packages/pkgcheck/reporters.
                        : py", line 84, in _process_report
ERROR concurrent.futures:     ': ', s, result.desc)
ERROR concurrent.futures:   File
                        : "/usr/lib/python3.7/site-packages/snakeoil/formatters
                        : .py", line 238, in write
ERROR concurrent.futures:     self._write_prefix(wrap)
ERROR concurrent.futures:   File
                        : "/usr/lib/python3.7/site-packages/snakeoil/formatters
                        : .py", line 188, in _write_prefix
ERROR concurrent.futures:     self.stream.write(thing)
ERROR concurrent.futures: ValueError: write to closed file

**Comment by mgorny** [comment]
Nevermind, doesn't happen anymore with -9999.

**Comment by mgorny** [comment]
My bad, I can actually reproduce with more complex pipeline:

```
$ git grep -l RESTRICT.*mirror $(<profiles/categories) | grep '^g' | cut -d/ -f1-2 | uniq | PKGCHECK_ARGS="--net --git-disable -c HomepageUrlCheck,FetchablesUrlCheck -k DeadSrcUrl" xargs ~/bin/file-pkgcheck 
Exception in thread ThreadPoolExecutor-1_0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.7/site-packages/pkgcheck/checks/network.py", line 186, in _done
    self.options.reporter.report(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 63, in run
    self.future.set_result(result)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 524, in set_result
    self._invoke_callbacks()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 326, in _invoke_callbacks
    LOGGER.exception('exception calling callback for %r', self)
  File "/usr/lib/python3.7/logging/__init__.py", line 1413, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 216, in emit
    self.out.write(line, wrap=True)
  File "/usr/lib/python3.7/site-packages/snakeoil/formatters.py", line 238, in write
    self._write_prefix(wrap)
  File "/usr/lib/python3.7/site-packages/snakeoil/formatters.py", line 188, in _write_prefix
    self.stream.write(thing)
ValueError: write to closed file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 99, in _worker
    _base.LOGGER.critical('Exception in worker', exc_info=True)
  File "/usr/lib/python3.7/logging/__init__.py", line 1425, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/lib/python3.7/site-packages/snakeoil/cli/tool.py", line 216, in emit
    self.out.write(line, wrap=True)
  File "/usr/lib/python3.7/site-packages/snakeoil/formatters.py", line 238, in write
    self._write_prefix(wrap)
  File "/usr/lib/python3.7/site-packages/snakeoil/formatters.py", line 188, in _write_prefix
    self.stream.write(thing)
ValueError: write to closed file

```

**Comment by radhermit** [comment]
Yep, not overly surprising as the current implementation using callbacks and the reporter instance directly is super hacky.

I need to rewrite it to send results back to a reporter used in a single thread, probably will tie into more support towards parallelization, i.e. returning future/task objs asynchronously that get awaited and rendered as necessary.
