### ISSUE TITLE
pkgcheck-0.7.0 exhausts memory on ::haskell overlay (OOM?)

### ISSUE THREAD

**Issue by trofi** [pkgcore/pkgcheck#178]
Seems to have regressed compared to `0.6.9`. Repo: https://github.com/gentoo-haskell/gentoo-haskell/

Checking as: `pkgcheck scan --repo=haskell --jobs=$(nproc)` (seems to behave the same without `--jobs` specificed).

`pkgcheck` used to finish in 6 minutes (first task in each build of https://travis-ci.org/gentoo-haskell/gentoo-haskell/builds), not it OOMs after 323 minutes as:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/scripts/__init__.py", line 30, in run
    sys.exit(tool())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/snakeoil/cli/tool.py", line 182, in main
    self.handle_exec_exception(e)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/snakeoil/cli/tool.py", line 167, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/scripts/pkgcheck.py", line 482, in _scan
    base.Cache.update_caches(options, caches)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/base.py", line 158, in update_caches
    ret.append(future.result())
  File "/opt/python/3.6.7/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/python/3.6.7/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/python/3.6.7/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/git.py", line 415, in update_cache
    git_repo = ParsedGitRepo(repo, commit, debug=self.options.debug)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/git.py", line 54, in __init__
    self._pkg_changes(**kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/git.py", line 162, in _pkg_changes
    for pkg in self.parse_git_log(self.location, cmd, pkgs=True, **kwargs):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkgcheck/git.py", line 135, in parse_git_log
    message.append(line)
MemoryError
```

Roll back to `0.6.9` helps.

**Comment by radhermit** [comment]
First off, if you're using pkgcheck in a CI environment I'd highly recommend using the --git-disable option which would probably skip this issue entirely. Otherwise, you're probably rebuilding the git pkg cache for every run that is used for results you probably don't care about on a CI run.

**Comment by radhermit** [comment]
In essence, your CI pkgcheck run is probably spending a few wasted minutes building a cache for every run that relates to results you don't care about, so if I were you I'd try using the --git-disable option with pkgcheck-0.7.0.

**Comment by radhermit** [comment]
On a further thought, it might make sense to have a global --cache option to toggle cache creation/support since generally CI instances won't find them useful unless you're properly saving the generated cache files in CI storage so they're reloaded for future instances and you're not just regenerating the entire cache every run.

**Comment by trofi** [comment]
I can try tweaking CI flags. I planned to copy in caches eventually and was lazy not to tweak things too much.

Even on my desktop `pkgcheck scan --repo=haskell --jobs=$(nproc)` takes at last 40 minutes and 10GB RAM (I did not wait for completion). Is that amount of resource usage expected and I should wait it over?

**Comment by radhermit** [comment]
Oh, I wasn't implying this isn't a bug, just didn't know if you wanted to work around it in a different fashion before I look into it. :smile:
