### ISSUE TITLE
KeyError: <Scope desc='commit' @0x7f7b60efd6a0>

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#197]
CI just hit this:

```
+ timeout -k 30s 30m pkgcheck scan -r gentoo --reporter XmlReporter -p stable,dev
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/__init__.py", line 30, in run
    sys.exit(tool())
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib64/python3.6/site-packages/pkgcheck/cli.py", line 12, in main
    return super().main()
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 182, in main
    self.handle_exec_exception(e)
  File "/usr/lib64/python3.6/site-packages/snakeoil/cli/tool.py", line 167, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/scripts/pkgcheck.py", line 577, in _scan
    reporter(pipe, sort=options.sorted)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/reporters.py", line 57, in __call__
    self.report(result)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/reporters.py", line 80, in _add_report
    self.process(result)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/reporters.py", line 263, in _process_report
    self.out.write(self.scope_map[result.scope] % d)
KeyError: <Scope desc='commit' @0x7f7b60efd6a0>
```

**Comment by radhermit** [comment]
I'm somewhat confused how a general repo scan is hitting any commit-related results as those should only be enabled when --commits is passed so I assume the bug causing this is somewhere else as well.

**Comment by radhermit** [comment]
I think I figured out why this might have been getting triggered so it should be fixed in https://github.com/pkgcore/pkgcheck/commit/3e0878edd6e8fdaf23b08dfd3ca0843567f44874.
