### ISSUE TITLE
Crash when maintainer email is empty

### ISSUE THREAD

**Issue by lucianposton** [pkgcore/pkgcheck#212]
pkgcheck is crashing from an unhandled exception from pkgcore due to an empty maintainer email/name in metadata.xml, such as the default one created by app-vim/gentoo-syntax.

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkgcheck/pipeline.py", line 71, in _run_checks
    results.extend(pipe.run(restrict))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/pipeline.py", line 189, in run
    yield from check.feed(item)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/checks/metadata.py", line 472, in feed
    local_use = pkg.local_use
  File "/usr/lib64/python3.6/site-packages/snakeoil/klass.py", line 373, in __call__
    return self.getter(obj)
  File "/usr/lib64/python3.6/site-packages/snakeoil/currying.py", line 71, in callit
    return func(*(moreargs + args), **morekwargs)
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/repo_objs.py", line 95, in _generic_attr
    self._parse_xml()
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/repo_objs.py", line 163, in _parse_xml
    MetadataXml._parse_xml(self, open(self._source, "rb", 32768))
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/repo_objs.py", line 128, in _parse_xml
    maint_type=x.get('type')))
  File "/usr/lib64/python3.6/site-packages/pkgcore/ebuild/repo_objs.py", line 59, in __init__
    raise ValueError('need at least one of name and email')
ValueError: need at least one of name and email
```

**Comment by radhermit** [comment]
Should have been fixed in https://github.com/pkgcore/pkgcore/commit/e1a67fb68018dda6dd0db0ae808d697a760eb38c as mentioned in the related pr.
