### ISSUE TITLE
Crash on `pkgcheck scan --commits` after `git mv`

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#215]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/pkgcheck/pipeline.py", line 71, in _run_checks
    results.extend(pipe.run(restrict))
  File "/usr/lib64/python3.6/site-packages/pkgcheck/pipeline.py", line 189, in run
    yield from check.feed(item)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/checks/git.py", line 304, in feed
    yield from self.modified_checks(modified)
  File "/usr/lib64/python3.6/site-packages/pkgcheck/checks/git.py", line 283, in modified_checks
    new_pkg = self.repo.match(pkg.versioned_atom)[0]
IndexError: list index out of range
```

I seem to be able to replicate this after using `git mv`, commit, then running `pkgcheck scan --commits`.

**Comment by radhermit** [comment]
Do you happen to have an example commit that causes this? I tried a basic package move and couldn't reproduce it, but can see how the code could fail.

**Comment by juippis** [comment]
Going back to check my commits would be guessing now, although I'm pretty sure one recent CI breakage happened because I couldn't run pkgcheck due to this. 

Next time it happens, I'll link the commit. 
What I usually do is, is 
```
git mv pkg-1.ebuild pkg-1-r1.ebuild
edit pkg-1-r1.ebuild
git add pkg-1-r1.ebuild
git commit
```

I guess if I only do `git mv, git commit` it doesn't crash.
