### ISSUE TITLE
circular import problem with pkgcheck.reporters

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#220]
```
>>> import pkgcheck.reporters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/pkgcheck/reporters.py", line 16, in <module>
    from . import base, objects, results
  File "/usr/lib/python3.8/site-packages/pkgcheck/objects.py", line 17, in <module>
    from . import _const as _defaults
  File "/usr/lib/python3.8/site-packages/pkgcheck/_const.py", line 5, in <module>
    REPORTERS = (('BinaryPickleStream', reporters.BinaryPickleStream), ('CsvReporter', reporters.CsvReporter), ('FancyReporter', reporters.FancyReporter), ('FormatReporter', reporters.FormatReporter), ('JsonReporter', reporters.JsonReporter), ('JsonStream', reporters.JsonStream), ('NullReporter', reporters.NullReporter), ('PickleStream', reporters.PickleStream), ('StrReporter', reporters.StrReporter), ('XmlReporter', reporters.XmlReporter))
AttributeError: partially initialized module 'pkgcheck.reporters' has no attribute 'BinaryPickleStream' (most likely due to a circular import)
```

Apparently can be worked around by importing `pkgcheck.checks` first but that kinda sucks.

**Comment by radhermit** [comment]
It's not really assumed that there's a public API for consumption yet until https://github.com/pkgcore/pkgcheck/issues/52 is worked on.
