### ISSUE TITLE
pkgcheck scan: fails on Python 3.8 on macOS (multiprocessing method is now 'spawn')

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#254]
Python 3.8 [flipped](https://docs.python.org/3/whatsnew/3.8.html#multiprocessing) the default multiprocessing start [method](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods) to 'spawn' on macOS. This has caused similar issues in [Portage](https://bugs.gentoo.org/758230).

I've pasted the backtrace below. Works fine if I use Python 3.7 instead.

Note that these errors should be reproducible on Linux by using multiprocessing.[set_start_method](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method)('spawn').

```
$ pkgcheck --version
pkgcheck 0.7.9 -- extended version info unavailable
```

```
$ pkgcheck scan --arch=x64-macos --keywords=NonsolvableDepsInExp,DroppedKeywords
Traceback (most recent call last):
  File "/Users/sam/Gentoo/usr/lib/python-exec/python3.8/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/cli.py", line 22, in main
    return super().main()
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/scripts/pkgcheck.py", line 536, in _scan
    ret.append(reporter(pipe))
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/reporters.py", line 31, in __call__
    for result in pipe:
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/pipeline.py", line 97, in __iter__
    p.start()
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/sam/Gentoo/usr/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Pipeline._create_runners.<locals>.<lambda>'
```

**Comment by radhermit** [comment]
Just a note to those interested, I wrote pkgcheck's parallelism support with forking in mind so the work to support this probably won't be trivial and will require restructuring checks, how they're initialized, and more work in pkgcore similar to what was necessary for initially supporting multiprocessing using the fork start method.

With that in mind, I don't see myself putting time into this unless the spawn start method becomes the default on Linux because I don't own/use any Apple or Windows machines with pkgcheck.

If someone else wants to put in the work and switch the default start method so testing would be more likely to cover potential Mac issues, I would be fine with that if benchmarks show a negligible performance hit.

**Comment by radhermit** [comment]
Closing this since I don't think the rewrite work required to make the spawn start method work will ever be worth it.

**Comment by thesamesam** [comment]
Agreed, I'm happy with forcing fork.
