### ISSUE TITLE
pkgcheck crash inside lxc container with sem_open error

### ISSUE THREAD

**Issue by epsilon-0** [pkgcore/pkgcheck#270]
pkgcheck scan crashes inside an lxc container with 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.8/site-packages/pkgcheck/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.8/site-packages/pkgcheck/cli.py", line 22, in main
    return super().main()
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.8/site-packages/pkgcheck/scripts/pkgcheck.py", line 535, in _scan
    pipe = Pipeline(options, scan_scope, restrict)
  File "/usr/lib/python3.8/site-packages/pkgcheck/pipeline.py", line 42, in __init__
    self._results_q = SimpleQueue()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

Let me know what I can do to help.

**Comment by epsilon-0** [comment]
apologies, it seems like this is an openrc error - https://github.com/OpenRC/openrc/issues/272
