### ISSUE TITLE
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#276]
```
ERROR concurrent.futures: exception calling callback for <Future at 0x7f73ae18eb20 state=finished returned RedirectedUrl>
ERROR concurrent.futures: Traceback (most recent call last):
ERROR concurrent.futures:   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_callbacks
ERROR concurrent.futures:     callback(self)
ERROR concurrent.futures:   File "/usr/lib/python3.9/site-packages/pkgcheck/checks/network.py", line 182, in task_done
ERROR concurrent.futures:     result = result._create(**result._attrs, pkg=pkg)
ERROR concurrent.futures:   File "/usr/lib/python3.9/site-packages/pkgcheck/results.py", line 62, in _create
ERROR concurrent.futures:     return cls(**kwargs)
ERROR concurrent.futures:  File "/usr/lib/python3.9/site-packages/pkgcheck/checks/network.py", line 51, in __init__
ERROR concurrent.futures:     super().__init__(**kwargs)
ERROR concurrent.futures:   File "/usr/lib/python3.9/site-packages/pkgcheck/results.py", line 204, in __init__
ERROR concurrent.futures:     super().__init__(pkg, **kwargs)
ERROR concurrent.futures:   File "/usr/lib/python3.9/site-packages/pkgcheck/results.py", line 182, in __init__
ERROR concurrent.futures:     super().__init__(pkg, **kwargs)
ERROR concurrent.futures:   File "/usr/lib/python3.9/site-packages/pkgcheck/results.py", line 163, in __init__
ERROR concurrent.futures:     super().__init__(**kwargs)
ERROR concurrent.futures: TypeError: object.__init__() takes exactly one argument (the instance to initialize)

```

**Comment by mgorny** [comment]
That's with `pkgcheck scan --commits   --net`

**Comment by mgorny** [comment]
This doesn't seem to resolve the problem. Still getting the same backtrace with -9999.

**Comment by radhermit** [comment]
> This doesn't seem to resolve the problem. Still getting the same backtrace with -9999.

Can you add information of which pkgs you're committing to where it triggers?

**Comment by mgorny** [comment]
Been doing random Python version bumps.

```
4efe67ca08bc dev-python/cftime: Bump to 1.4.1
bd61ce220fe3 dev-python/statsmodels: Bump to 0.12.2
---
cf6be04a6d7f dev-python/bleach: Bump to 3.3.0
0c950d4e36b2 dev-python/fastjsonschema: Bump to 2.15.0
d78b509bafee dev-python/croniter: Bump to 1.0.6
24ab302c1f4c dev-python/ipython: Bump to 7.20.0
```

**Comment by mgorny** [comment]
Happened again with:
```
3161fa52774a dev-python/construct: Bump to 2.10.59
494f18fb86ce dev-python/bracex: Bump to 2.1.0
b8d5abbec53d dev-python/python-stdnum: Bump to 1.16
180a81a2777a dev-python/apispec: Add python@ as co-maint
72d19d2fdf77 dev-python/apispec: Bump to 4.2.0

```
