### ISSUE TITLE
TypeError: restrict must be a pkgcore.restriction.restrictions.base instance: got frozenset({'profiles/package.mask'})

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#279]
```
$ pkgcheck scan --commits --net
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcheck/pipeline.py", line 249, in _run
    self._queue_work(sync_pipes, work_q, sync_restricts)
  File "/usr/lib/python3.9/site-packages/pkgcheck/pipeline.py", line 181, in _queue_work
    for restrict in unversioned_source.itermatch(restriction):
  File "/usr/lib/python3.9/site-packages/pkgcheck/sources.py", line 368, in itermatch
    for pkg in super().itermatch(restrict, **kwargs):
  File "/usr/lib/python3.9/site-packages/pkgcheck/sources.py", line 240, in itermatch
    yield from super().itermatch(restrict, raw_pkg_cls=RawCPV, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkgcheck/sources.py", line 63, in itermatch
    return self.source.itermatch(restrict, sorter=sorter, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/repository.py", line 571, in itermatch
    return super().itermatch(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkgcore/repository/prototype.py", line 254, in itermatch
    raise TypeError(
TypeError: restrict must be a pkgcore.restriction.restrictions.base instance: got frozenset({'profiles/package.mask'})
Sandboxed process killed by signal: Broken pipe
```

**Comment by mgorny** [comment]
Relevant set of commits:

```
8800041abd11 sys-kernel/gentoo-kernel-bin: Bump to 5.4.96
33d702c1f1fb sys-kernel/gentoo-kernel-bin: Bump to 5.10.14
0ca12ba03035 dev-python/numpy: Bump to 1.20.1
ff3c4742bc6b virtual/dist-kernel: Bump to 5.4.96
8da4495158ed sys-kernel/gentoo-kernel: Bump to 5.4.96
3082939830c8 sys-kernel/vanilla-kernel: Bump to 5.4.96
f6aa5fa380df virtual/dist-kernel: Bump to 5.10.14
f5efeb88d697 sys-kernel/gentoo-kernel: Bump to 5.10.14
cbbee4a4c7e3 sys-kernel/vanilla-kernel: Bump to 5.10.14
```

**Comment by mgorny** [comment]
More precisely, this one:

```
commit 0ca12ba030358b6e399d2537eb1b5ebf1cbfc41f
Author:     Michał Górny <mgorny@gentoo.org>
AuthorDate: 2021-02-07 22:57:44 +0100
Commit:     Michał Górny <mgorny@gentoo.org>
CommitDate: 2021-02-08 00:04:47 +0100

    dev-python/numpy: Bump to 1.20.1
    
    Signed-off-by: Michał Górny <mgorny@gentoo.org>

 dev-python/numpy/Manifest                                    |   1 +
 dev-python/numpy/files/numpy-1.20.1-no-hardcode-blasv2.patch |  50 +++++++++++++++++++++++++++
 dev-python/numpy/numpy-1.20.1.ebuild                         | 145 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 profiles/package.mask                                        |   5 +++
 4 files changed, 201 insertions(+)
```
