### ISSUE TITLE
Failed to dlopen(.../_bash-lang.so) on macOS (Prefix)

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#299]
```
$ pkgcheck scan                                                                                                                 2 ↵
Traceback (most recent call last):
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/addons/__init__.py", line 309, in init_addon
    addon = addons_map[cls]
KeyError: <class 'pkgcheck.addons.BashAddon'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sam/Gentoo/usr/lib/python-exec/python3.8/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/cli.py", line 21, in main
    return super().main()
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 431, in _scan
    pipe = Pipeline(options)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/pipeline.py", line 36, in __init__
    self._pipes = self._create_runners()
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/pipeline.py", line 92, in _create_runners
    checks = init_checks(
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/checks/__init__.py", line 187, in init_checks
    addon = addons.init_addon(cls, options, addons_map)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/addons/__init__.py", line 323, in init_addon
    addon = addons_map[cls] = cls(options, **kwargs)
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/addons/__init__.py", line 297, in __init__
    self.bash = Language(lib_path, 'bash')
  File "/Users/sam/Gentoo/usr/lib/python3.8/site-packages/tree_sitter/__init__.py", line 81, in __init__
    self.lib = cdll.LoadLibrary(library_path)
  File "/Users/sam/Gentoo/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Users/sam/Gentoo/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/_bash-lang.so, 6): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4copyEPcmm
  Referenced from: /Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/_bash-lang.so
  Expected in: flat namespace
 in /Users/sam/Gentoo/usr/lib/python3.8/site-packages/pkgcheck/_bash-lang.so

$ pkgcheck --version
pkgcheck 0.9.3-1-g26ffd88 -- Fri, 5 Mar 2021 19:48:30 -0700
```

I've attached the 
[build log](https://github.com/pkgcore/pkgcheck/files/6094742/build.log) of pkgcheck too.

I think it must be mixing up with system libraries (i.e. non-Prefix), as when building, it's putting /usr/local/lib at the beginning of the include path, which is a no-no for Prefix.

**Comment by radhermit** [comment]
It appears that the c++ library isn't getting detected and thus not being linked in (see https://github.com/pkgcore/pkgcheck/blob/master/src/pkgcheck/utils.py#L148). That code probably should fallback to an exception if no c++ library is found or something along those lines.

If you want to mess around before I get to it, you could try seeing what the string for the c++ library should be for the system (i.e. play around with find_library()).

**Comment by thesamesam** [comment]
Apparently this is complicated.

- If I force ```find_library("stdc++")```, it works because GCC provides that within my Prefix.
- Python 3.8 hasn't yet received backports for find_library issues related to macOS 11.
- Python 3.9 is _slightly_ better in that it detects and tries to use libcxx. But that's not available in the Prefix in my case -- only on the host.

So, we need some way of persuading Python to only consider within the Prefix. I'll play with building Python with some patches next.

**Comment by thesamesam** [comment]
Here's a hacky patch for now until I mess with patching Python to respect our library dirs on macOS:
```
diff --git a/src/pkgcheck/utils.py b/src/pkgcheck/utils.py
index 5a4b9f6d..4b459076 100644
--- a/src/pkgcheck/utils.py
+++ b/src/pkgcheck/utils.py
@@ -146,10 +146,7 @@ def build_library(output_path, repo_paths):

     compiler = new_compiler()
     if cpp:
-        if find_library("stdc++"):
-            compiler.add_library("stdc++")
-        elif find_library("c++"):
-            compiler.add_library("c++")
+        compiler.add_library("stdc++")

     if max(source_mtimes) <= output_mtime:
         return False
```

**Comment by thesamesam** [comment]
For completeness: I've now filed a [bug](https://bugs.gentoo.org/775839) in Gentoo with a patch to fix the Prefix side of things.
