### ISSUE TITLE
TestScanApi.test_sigint_handling hangs on HPPA and Sparc

### ISSUE THREAD

**Issue by DerDakon** [pkgcore/pkgcheck#311]
I have to kill it so the testsuite will go on.

```ps aux``` output:

```
portage  13557  7.1  0.1  60576 46488 pts/0    S+   11:44   0:35 python3.8 setup.py test --verbose
portage  14248  0.0  0.0      0     0 pts/0    Z+   11:45   0:00 [python3.8] <defunct>
```

```strace``` output:

```
strace: Process 13557 attached
restart_syscall(<... resuming interrupted restart_syscall ...>) = -1 EINTR (Interrupted system call)
read(15, 
```

When I kill the parent process the testsuite continues, this is the error output I get at the end:

```
self = <tests.test_api.TestScanApi object at 0xf6c7e820>, repo = <pkgcore.pytest.plugin.EbuildRepo object at 0xf6c7e9a0>

    def test_sigint_handling(self, repo):
        """Verify SIGINT is properly handled by the parallelized pipeline."""
    
        def run(queue):
            """Pipeline test run in a separate process that gets interrupted."""
            import sys
            import time
            from functools import partial
            from unittest.mock import patch
    
            from pkgcheck import scan
    
            def sleep():
                """Notify testing process then sleep."""
                queue.put('ready')
                time.sleep(100)
    
            with patch('pkgcheck.pipeline.Pipeline.__iter__') as fake_iter:
                fake_iter.side_effect = partial(sleep)
                try:
                    iter(scan([repo.location]))
                except KeyboardInterrupt:
                    queue.put(None)
                    sys.exit(0)
                queue.put(None)
                sys.exit(1)
    
        mp_ctx = multiprocessing.get_context('fork')
        queue = mp_ctx.SimpleQueue()
        p = mp_ctx.Process(target=run, args=(queue,))
        p.start()
        # wait for pipeline object to be fully initialized then send SIGINT
>       for _ in iter(queue.get, None):

tests/test_api.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/multiprocessing/queues.py:356: in get
    res = self._reader.recv_bytes()
/usr/lib/python3.8/multiprocessing/connection.py:216: in recv_bytes
    buf = self._recv_bytes(maxlength)
/usr/lib/python3.8/multiprocessing/connection.py:414: in _recv_bytes
    buf = self._recv(4)
/usr/lib/python3.8/multiprocessing/connection.py:379: in _recv
    chunk = read(handle, remaining)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ebp = None, args = (15, <frame at 0xf6f54308, file '/usr/lib/python3.8/multiprocessing/connection.py', line 379, code _recv>)

    def chuck_TermInterrupt(ebp, *args):
        """Event handler for SIGTERM."""
        if ebp is None:
            # main python process got SIGTERM-ed, shutdown everything
            for ebp in chain(active_ebp_list, inactive_ebp_list):
                drop_ebuild_processor(ebp)
                ebp.shutdown_processor()
>           raise SystemExit(128 + signal.SIGTERM)
E           SystemExit: 143

/usr/lib/python3.8/site-packages/pkgcore/ebuild/processor.py:288: SystemExit
----------------------------------------------------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------------------------------------------------------
Process ForkProcess-1:
Traceback (most recent call last):
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/addons/__init__.py", line 309, in init_addon
    addon = addons_map[cls]
KeyError: <class 'pkgcheck.addons.BashAddon'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/tests/test_api.py", line 47, in run
    iter(scan([repo.location]))
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/api.py", line 39, in scan
    return Pipeline(options)
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/pipeline.py", line 36, in __init__
    self._pipes = self._create_runners()
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/pipeline.py", line 92, in _create_runners
    checks = init_checks(
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/checks/__init__.py", line 187, in init_checks
    addon = addons.init_addon(cls, options, addons_map)
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/addons/__init__.py", line 323, in init_addon
    addon = addons_map[cls] = cls(options, **kwargs)
  File "/var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/addons/__init__.py", line 297, in __init__
    self.bash = Language(lib_path, 'bash')
  File "/usr/lib/python3.8/site-packages/tree_sitter/__init__.py", line 81, in __init__
    self.lib = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /var/tmp/portage/dev-util/pkgcheck-0.9.2/work/pkgcheck-0.9.2-python3_8/src/pkgcheck/_bash-lang.so: wrong ELF class: ELFCLASS64

```

**Comment by radhermit** [comment]
Already fixed in https://github.com/pkgcore/pkgcheck/commit/2882e76070b509387f3157bbb404812f0df40942.
