### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [pkgcore/pkgcheck#346]
Running `pkgcheck scan` in a folder with an ebuild named `nanos6-2.6-r2-p1.ebuild` led to
```
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcheck/pipeline.py", line 227, in _run
    self._queue_work(sync_pipes, work_q)
  File "/usr/lib/python3.9/site-packages/pkgcheck/pipeline.py", line 168, in _queue_work
    for restrict in versioned_source.itermatch(restriction):
  File "/usr/lib/python3.9/site-packages/pkgcheck/sources.py", line 378, in itermatch
    for pkg in super().itermatch(restrict, **kwargs):
  File "/usr/lib/python3.9/site-packages/pkgcheck/sources.py", line 247, in itermatch
    yield from super().itermatch(restrict, raw_pkg_cls=RawCPV, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkgcore/repository/prototype.py", line 298, in _internal_match
    for pkg in self._internal_gen_candidates(candidates, **kwargs):
  File "/usr/lib/python3.9/site-packages/pkgcore/repository/prototype.py", line 295, in _internal_gen_candidates
    yield from sorter(pkg_filter(pkgs))
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/repository.py", line 474, in _pkg_filter
    pkg = next(pkgs)
  File "/usr/lib/python3.9/site-packages/pkgcore/repository/prototype.py", line 288, in <genexpr>
    pkgs = (raw_pkg_cls(cp[0], cp[1], ver) for ver in self.versions.get(cp, ()))
  File "<string>", line 6, in __init__
  File "/usr/lib/python3.9/site-packages/pkgcheck/packages.py", line 24, in __post_init__
    object.__setattr__(self, 'revision', cpv.Revision(revision))
  File "/usr/lib/python3.9/site-packages/pkgcore/ebuild/cpv.py", line 62, in __init__
    self._revint = int(self.data)
ValueError: invalid literal for int() with base 10: '2-p1'
```

**Comment by mgorny** [comment]
Well, that's obviously invalid version string.

**Comment by Alessandro-Barbieri** [comment]
ok but the program shouldn't crash

**Comment by mgorny** [comment]
Sure but this isn't a high priority for me right now.
