### ISSUE TITLE
--commit -f latest: AttributeError: '_GitCommitPkg' object has no attribute 'live'

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#380]
I was hoping to hack around a cheap way to get `PythonCompatUpdate` reports for packages I've prepared to push but…

```pytb
$ pkgcheck scan --commit  -f latest
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkgcheck/pipeline.py", line 186, in _run_checks
    if results := sorted(chain.from_iterable(
  File "/usr/lib/python3.10/site-packages/pkgcheck/runners.py", line 67, in run
    for item in self.source.itermatch(restrict):
  File "/usr/lib/python3.10/site-packages/pkgcheck/sources.py", line 140, in itermatch
    yield from self._pkg_filter(super().itermatch(restrict, **kwargs))
  File "/usr/lib/python3.10/site-packages/pkgcheck/sources.py", line 123, in __next__
    if pkg.live:
AttributeError: '_GitCommitPkg' object has no attribute 'live'
```

**Comment by mgorny** [comment]
(limiting checks via e.g. `-k PythonCompatUpdate` avoids the problem though)
