### ISSUE TITLE
Safe directory feature in >= git 2.35.2 breaks git integration

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#412]
With >= git 2.35.2, the "safe directory" feature prevents use of `pkgdev commit` (and other `pkgcheck` git integration). It's not possible to add it as a safe directory like the error suggests because of https://github.com/pkgcore/pkgcheck/commit/ad207610a254c7a502d5760e2e33cf442448b3c4 (added for #336).

```
~/git/overlay/dev-vcs/git $ pkgdev commit
pkgdev commit: error: failed running git log: fatal: unsafe repository ('/var/db/repos/gentoo' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /var/db/repos/gentoo
```

```
~/git/overlay/dev-vcs/git $ pkgdev commit -v --debug
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/__init__.py", line 288, in init_addon
    addon = addons_map[cls]
KeyError: <class 'pkgcheck.addons.git.GitAddon'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/git.py", line 559, in update_cache
    self.pkg_history(
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/git.py", line 510, in pkg_history
    for pkg in GitRepoPkgs(repo.location, commit_range, local=local):
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/git.py", line 207, in __init__
    super().__init__(*args)
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/git.py", line 133, in __init__
    next(self.git_log)
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/git.py", line 102, in __next__
    raise GitError(f'failed running git log: {error}')
pkgcheck.addons.git.GitError: failed running git log: fatal: unsafe repository ('/var/db/repos/gentoo' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /var/db/repos/gentoo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/pkgdev", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.10/site-packages/pkgdev/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/usr/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.10/site-packages/pkgdev/cli.py", line 22, in main
    return super().main()
  File "/usr/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.10/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.10/site-packages/pkgdev/scripts/pkgdev_commit.py", line 800, in _commit
    pipe = scan(options.scan_args)
  File "/usr/lib/python3.10/site-packages/pkgcheck/api.py", line 44, in scan
    return Pipeline(options)
  File "/usr/lib/python3.10/site-packages/pkgcheck/pipeline.py", line 36, in __init__
    self._pipes = self._create_runners()
  File "/usr/lib/python3.10/site-packages/pkgcheck/pipeline.py", line 92, in _create_runners
    checks = init_checks(
  File "/usr/lib/python3.10/site-packages/pkgcheck/checks/__init__.py", line 187, in init_checks
    addon = addons.init_addon(cls, options, addons_map)
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/__init__.py", line 307, in init_addon
    addon.update_cache(force=force_cache)
  File "/usr/lib/python3.10/site-packages/pkgcheck/addons/git.py", line 563, in update_cache
    raise PkgcheckUserException(str(e))
pkgcheck.base.PkgcheckUserException: failed running git log: fatal: unsafe repository ('/var/db/repos/gentoo' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /var/db/repos/gentoo
```

```
$ git --version
git version 2.37.0

$ pkgcheck --version
pkgcheck 0.10.12-8-g41f75fc -- Mon, 13 Jun 2022 21:48:48 +0200

$ pkgdev --version
pkgdev 0.2.1-2-g9f60576 -- Fri, 10 Jun 2022 16:36:57 +0300
```

**Comment by laumann** [comment]
cc @laumann
