### ISSUE TITLE
pkgcheck scan fails when Manifest file is missing

### ISSUE THREAD

**Issue by r7l** [pkgcore/pkgcheck#530]
Writing a new Ebuild or deleting the Manifest file renders `pkgcheck scan` unable to run checks for the existing Ebuilds in that directory:

```
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkgcore/ebuild/digest.py", line 101, in _pull_manifest
    data = parse_manifest(self.path, ignore_gpg=self._gpg)
  File "/usr/lib/python3.10/site-packages/pkgcore/ebuild/digest.py", line 52, in parse_manifest
    i = f = open(source, "r", 32768)
FileNotFoundError: [Errno 2] No such file or directory: '/home/r7l/overlays/r7l-overlay/dev-python/passpy/Manifest'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkgcheck/pipeline.py", line 186, in _run_checks
    if results := sorted(chain.from_iterable(
  File "/usr/lib/python3.10/site-packages/pkgcheck/runners.py", line 70, in run
    yield from check.feed(item)
  File "/usr/lib/python3.10/site-packages/pkgcheck/checks/repo_metadata.py", line 575, in feed
    manifest_distfiles = set(pkg_manifest.distfiles.keys())
  File "/usr/lib/python3.10/site-packages/pkgcore/ebuild/digest.py", line 173, in distfiles
    self._pull_manifest()
  File "/usr/lib/python3.10/site-packages/pkgcore/ebuild/digest.py", line 104, in _pull_manifest
    raise errors.ParseChksumError(self.path, e) from e
pkgcore.package.errors.ParseChksumError: failed parsing 'dev-python/passpy/Manifest': [Errno 2] No such file or directory: '/home/r7l/overlays/r7l-overlay/dev-python/passpy/Manifest'
```

There are currently a few issues with pkgdev silently failing to build Manifest files if the Ebuild has issues ([here](https://github.com/pkgcore/pkgdev/issues/108) and [here](https://github.com/pkgcore/pkgdev/issues/55)). It would help if it would be possible to scan for these issues using `pkgcheck scan` even if there is no Manifest file.

**Comment by arthurzam** [comment]
Info on reproduction:

1. Happens on `thin=false` repos
2. Deleting the manifest does trigger it
