### ISSUE TITLE
Another FileNotFoundError with --commits

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#563]
Pushed to https://github.com/mgorny/gentoo as `pkgcheck-crash` branch.

```
$ pkgcheck scan --commit 0ef5d597cab485d25c7fcf9733a329daab4ad07e..5d777e978c0ecaa4000656c1595acadb8d17a0da
dev-python/xlsxwriter
  UnstableOnly: for arches: [ hppa, sparc ], all versions are unstable: [ 3.0.7, 3.0.8, 3.0.9 ]
  PotentialStable: version 3.0.7: slot(0), stabled arches: [ amd64, arm, arm64, ppc, ppc64, x86 ], potentials: [ ~hppa, ~sparc ]
  RedundantVersion: version 3.0.8: slot(0) keywords are overshadowed by version: 3.0.9
  StableRequest: version 3.0.8: slot(0) no change in 33 days for unstable keywords: [ ~amd64, ~arm, ~arm64, ~ppc, ~ppc64, ~x86 ]

dev-python/urllib3
  PythonInlinePyPIURI: version 1.26.14: inline PyPI URI found matching pypi.eclass default, inherit the eclass, and remove SRC_URI instead
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkgcheck/pipeline.py", line 237, in _run
    if results := tuple(runner.run(restriction)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/runners.py", line 71, in run
    yield from check.feed(item)
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/git.py", line 500, in feed
    yield from self.modified_checks(modified, list(pkg_map["A"]))
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/git.py", line 387, in modified_checks
    old_pkg = modified_repo.match(pkg.versioned_atom)[0]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 224, in match
    return list(self.itermatch(atom, **kwds))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 314, in _internal_match
    for pkg in self._internal_gen_candidates(candidates, **kwargs):
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 309, in _internal_gen_candidates
    yield from sorter(pkg_filter(pkgs))
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/repository.py", line 576, in _pkg_filter
    if not pkg.is_supported:
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/klass.py", line 389, in __call__
    return self.getter(obj)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/package/base.py", line 95, in dynamic_getattr_dict
    val = functor(self)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/ebuild_src.py", line 289, in eapi
    i = fileutils.readlines_utf8(ebuild.path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/snakeoil/_fileutils.py", line 85, in native_readlines
    handle = open(mypath, mode, encoding=encoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp-pkgcheck-vh_mwcs2.repo/dev-python/tornado/tornado-6.2-r1.ebuild'
```

**Comment by mgorny** [comment]
Actually, the minimal range to reproduce is:

```
pkgcheck scan --commit a16cff3f8c3accadd712400075f32ce5692cc7ee..016f756a8e8f8b1740b9152c09e29cad8f2d8ad2
```

**Comment by arthurzam** [comment]
Reproduced using original command:

```bash
pkgcheck scan --commit 0ef5d597cab485d25c7fcf9733a329daab4ad07e..5d777e978c0ecaa4000656c1595acadb8d17a0da
```
