### ISSUE TITLE
Check "ProfileError" appears to be unsafe

### ISSUE THREAD

**Issue by ZeroChaos-** [pkgcore/pkgcheck#577]
If I had to guess, ProfileError check is probably finding something wrong with my profile and failing to handle it.
```
zero@theprophet metadata % cat pkgcheck.conf                                                                                                                 (git)-[master] 
[CHECKSETS]
PentooCI =
  #BadDependency
  #BadKeywords
  #BadPackageUpdate
  #BadProtocol
  #BadWhitespaceCharacter
  #BannedCharacter
  #ConflictingChksums
  #EclassBashSyntaxError
  #EqualVersions
  #InvalidBdepend
  #InvalidDepend
  #InvalidEapi
  #InvalidLicense
  #InvalidManifest
  #InvalidPN
  #InvalidPdepend
  #InvalidProperties
  #InvalidRdepend
  #InvalidRequiredUse
  #InvalidRestrict
  #InvalidSlot
  #InvalidSrcUri
  #InvalidUTF8
  #InvalidUseFlags
  #MissingLicense
  #MissingManifest
  #MissingSlash
  #MovedPackageUpdate
  #NonexistentProfilePath
  #NonsolvableDepsInStable
  ProfileError
  #PythonEclassError
  #SourcingError
  #UnknownCategoryDirs
  #UnknownLicenses
  #UnknownManifest
  #UnknownMirror
  #UnstatedIuse
  #VisibleVcsPkg
zero@theprophet metadata % pkgcheck scan --repo pentoo -C PentooCI --net --tasks=32 --jobs=32                                                                (git)-[master] 
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkgcheck/pipeline.py", line 191, in _run_checks
    if results := sorted(
                  ^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcheck/runners.py", line 71, in run
    yield from check.feed(item)
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/profiles.py", line 381, in feed
    yield from func(self, f, profile.node, data)
  File "/usr/lib/python3.11/site-packages/pkgcheck/checks/profiles.py", line 281, in _pkg_atoms
    if not self.search_repo.match(x):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 224, in match
    return list(self.itermatch(atom, **kwds))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/multiplex.py", line 168, in <genexpr>
    for match in repo.itermatch(restrict, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/ebuild/repository.py", line 599, in itermatch
    return super().itermatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkgcore/repository/prototype.py", line 258, in itermatch
    raise TypeError(
TypeError: restrict must be a pkgcore.restriction.restrictions.base instance: got True
```

**Comment by ZeroChaos-** [comment]
For clarity sake, I am running 0.10.23 plus https://github.com/pkgcore/pkgcheck/issues/576

**Comment by arthurzam** [comment]
OK, the breaking line is https://github.com/pentoo/pentoo-overlay/blob/master/profiles/pentoo/base/packages#L5 (a line of `-*` in `packages` file).

I don't know if this is a correct behavior by PMS? If yes, I'll be thankful for a link to that section. Otherwise I'll need help to understand the behavior and which portage extension enables it?
(In short, I don't know what this is, and I need some explanation so I can implement it).

**Comment by ZeroChaos-** [comment]
thanks again @arthurzam !
