### ISSUE TITLE
pkgcheck should use >tree-sitter-0.20.3

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#613]
This is with tree-sitter-0.20.3 with ::gentoo at 9a9621d863c8829b54cdd76124c94f83ddd006c5:
```console
~/g/app-shells/bash $ pkgcheck scan
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 191, in _run_checks
    if results := sorted(
                  ^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/runners.py", line 71, in run
    yield from check.feed(item)
  File "/usr/lib/python3.12/site-packages/pkgcheck/checks/reserved.py", line 144, in feed
    for used_name, *args, lineno in self._feed(pkg):
  File "/usr/lib/python3.12/site-packages/pkgcheck/checks/reserved.py", line 49, in _feed
    item.node_str(node.child_by_field_name("name")): node.start_point
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/bash/__init__.py", line 123, in node_str
    return self.data[node.start_byte : node.end_byte].decode("utf8")
                     ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_byte'
```

```console
$ pkgcheck --version
pkgcheck 0.10.26-4-gaa668df -- Wed, 2 Aug 2023 14:45:53 +0200
$ pmaint --version
pkgcore 0.12.23-4-g8d1a209 -- Mon, 21 Aug 2023 21:23:37 +0300
```

**Comment by thesamesam** [comment]
I recommend using `--jobs=1` or it gets confusing quickly.

With debugging prints added:
```console
~/g/app-shells/bash $ pkgcheck scan --jobs=1 --verbose --debug bash-5.1_p16-r6.ebuild
[...]
node=<Node type=variable_name, start_point=(50, 2), end_point=(50, 19)>
self=<<class 'pkgcore.ebuild.ebuild_src.package'> cpv='app-shells/bash-5.1_p16-r6' @0x7efcbb3d4830>
node=<Node type=variable_name, start_point=(51, 2), end_point=(51, 17)>
self=<<class 'pkgcore.ebuild.ebuild_src.package'> cpv='app-shells/bash-5.1_p16-r6' @0x7efcbb3d4830>
node=None
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 135, in __next__
    result = self._results.popleft()
             ^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/pkgcheck", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/scripts/__init__.py", line 48, in main
    run(os.path.basename(sys.argv[0]))
  File "/usr/lib/python3.12/site-packages/pkgcheck/scripts/__init__.py", line 40, in run
    sys.exit(tool())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/cli/tool.py", line 81, in __call__
    ret = self.main()
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/cli.py", line 20, in main
    return super().main()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/cli/tool.py", line 191, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.12/site-packages/snakeoil/cli/tool.py", line 176, in main
    exitstatus = func(self.options, self.out, self.err)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 518, in _scan
    for result in pipe:
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 156, in __next__
    self._kill_pipe(error=results.strip())
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 124, in _kill_pipe
    raise base.PkgcheckUserException(error)
pkgcheck.base.PkgcheckUserException: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 191, in _run_checks
    if results := sorted(
                  ^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/runners.py", line 71, in run
    yield from check.feed(item)
  File "/usr/lib/python3.12/site-packages/pkgcheck/checks/reserved.py", line 144, in feed
    for used_name, *args, lineno in self._feed(pkg):
  File "/usr/lib/python3.12/site-packages/pkgcheck/checks/reserved.py", line 49, in _feed
    item.node_str(node.child_by_field_name("name")): node.start_point
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/bash/__init__.py", line 125, in node_str
    return self.data[node.start_byte : node.end_byte].decode("utf8")
                     ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_byte'
```

**Comment by thesamesam** [comment]
Minimal reproducer:
```python
from tree_sitter import Language, Parser
from ctypes.util import find_library

syslib = find_library("tree-sitter-bash")
lang = Language(syslib, "bash")
parser = Parser()
parser.set_language(lang)
# the next lines does all the problems
tree = parser.parse(b"""
for ((my_patch_index=1; my_patch_index <= ${PLEVEL} ; my_patch_index++)) ; do
        :;
done
""")

query = lang.query
var_assign_query = query("(variable_assignment) @assign")

for node, _ in var_assign_query.captures(tree.root_node):
        print(node.child_by_field_name("name").start_byte)
```

**Comment by arthurzam** [comment]
Just for archive and information purpose, tree-sitter-bash did huge work for us to handle all of Gentoo repository, so we don't have any errors. Waiting for newest release (>0.20.3), bundle it, close relevant issues, and remove version cap from ebuild.

**Comment by arthurzam** [comment]
@thesamesam here are the results of the 2 runs. I already see some changes, which needs some updates in code (adding `strip()`, adding sorts to some fields, and such):

[ts-bash-0.19.0.json](https://github.com/pkgcore/pkgcheck/files/12499419/ts-bash-0.19.0.sorted.json.txt)
[ts-bash-0.20.4.json](https://github.com/pkgcore/pkgcheck/files/12499428/ts-bash-0.20.4.sorted.json.txt)
