### ISSUE TITLE
`FileNotFoundError`

### ISSUE THREAD

**Issue by kuraga** [pkgcore/pkgcheck#722]
```console
$ pkgcheck --debug --verbose scan --net --commits -C all
<...>
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 135, in __next__
    result = self._results.popleft()
             ^^^^^^^^^^^^^^^^^^^^^^^
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/pkgcheck", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/scripts/__init__.py", line 48, in main
    run(os.path.basename(sys.argv[0]))
  File "/usr/lib/python3.12/site-packages/pkgcheck/scripts/__init__.py", line 40, in run
    sys.exit(tool())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/cli/tool.py", line 81, in __call__
    ret = self.main()
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/cli.py", line 20, in main
    return super().main()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/cli/tool.py", line 191, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.12/site-packages/snakeoil/cli/tool.py", line 176, in main
    exitstatus = func(self.options, self.out, self.err)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 525, in _scan
    for result in pipe:
                  ^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 156, in __next__
    self._kill_pipe(error=results.strip())
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 124, in _kill_pipe
    raise base.PkgcheckUserException(error)
pkgcheck.base.PkgcheckUserException: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 237, in _run
    if results := tuple(runner.run(restriction)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/runners.py", line 71, in run
    yield from check.feed(item)
  File "/usr/lib/python3.12/site-packages/pkgcheck/checks/git.py", line 572, in feed
    yield from self.removal_checks(list(pkg_map["D"]))
  File "/usr/lib/python3.12/site-packages/pkgcheck/checks/git.py", line 400, in removal_checks
    old_keywords = set().union(*(p.keywords for p in removal_repo.match(pkg.unversioned_atom)))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/repository/prototype.py", line 212, in match
    return list(self.itermatch(atom, **kwds))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/repository/prototype.py", line 302, in _internal_match
    for pkg in self._internal_gen_candidates(candidates, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/repository/prototype.py", line 297, in _internal_gen_candidates
    yield from sorter(pkg_filter(pkgs))
  File "/usr/lib/python3.12/site-packages/pkgcore/ebuild/repository.py", line 586, in _pkg_filter
    if not pkg.is_supported:
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/klass.py", line 391, in __call__
    return self.getter(obj)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/package/base.py", line 95, in dynamic_getattr_dict
    val = functor(self)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcore/ebuild/ebuild_src.py", line 289, in eapi
    i = fileutils.readlines_utf8(ebuild.path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/snakeoil/_fileutils.py", line 85, in native_readlines
    handle = open(mypath, mode, encoding=encoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp-pkgcheck-yoplgma9.repo/net-im/viber/viber-21.8.0.11.ebuild'
```

But...
```console
$ git ls-files net-im/viber
```

There was `=viber/viber-21.8.0.11` in that repo but there is not now.

**Comment by arthurzam** [comment]
This isn't a good report. Please see the report template for `pkgcheck commits` issue.

**Comment by kuraga** [comment]
@arthurzam , you're right. I'm sorry about that.
I've updated the issue.

According to the fact the mentioned ebuild _changed_ after I had updated the tree, I thought about kind of... caches.
```
DEBUG pkgcheck: skipping calculate git repo cache update on non-default branch 'develop'
```
Can this DEBUG be the key? `=app-misc/geoclue-2.7.2` had been deleted but the cache haven't been updated.
Which caused the error.

Thanks very much.
